print("hello, world")
name = input()
print("hello there " + name)
print ("What's your favorite food")
food = input ()
print ("your favorite food is" + food)
print ("What's your favorite color")
color = input ()
print ("your favorite color is " + color)